#ifndef CONFIG_H_
#define CONFIG_H_

#define DENDRITE_SCK	PB7
#define DENDRITE_CSN	PB3
#define DENDRITE_MOSI	PB6
#define DENDRITE_MISO	PB5
#define DENDRITE_IRQ	PB4
#define DENDRITE_IRQ_I	PCINT4
#define DENDRITE_CE		PB2
	
#define DENDRITE_PIPE_LENGTH 32

#endif //CONFIG_H_