#ifndef _PRINTF_CONFIG_H_INCLUDED_
#define _PRINTF_CONFIG_H_INCLUDED_

#define PRINTF_NTOA_BUFFER_SIZE 4U
#define PRINTF_FTOA_BUFFER_SIZE 4U
#define PRINTF_DISABLE_SUPPORT_FLOAT
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T

#endif // _PRINTF_CONFIG_H_INCLUDED_
