#include <stdint.h>

// https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
char const* BtCompanyIdToString(uint16_t id) {
	switch (id) {
		case 0x0838: return "Etymotic Research, Inc.";
		case 0x0804: return "Andon Health Co.,Ltd";
		case 0x0801: return "CRONUS ELECTRONICS LTD";
		case 0x0800: return "Optek";
		case 0x07FF: return "maxon motor ltd.";
		case 0x07FE: return "BIROTA";
		case 0x07FD: return "JSK CO., LTD.";
		case 0x07FC: return "Renault SA";
		case 0x07FB: return "Access Co., Ltd";
		case 0x07FA: return "Klipsch Group, Inc.";
		case 0x07F9: return "Direct Communication Solutions, Inc.";
		case 0x07F8: return "quip NYC Inc.";
		case 0x07D4: return "Kano Computing Limited";
		case 0x0770: return "InnoCon Medical ApS";
		case 0x070C: return "Beijing Winner Microelectronics Co.,Ltd";
		case 0x0704: return "JBX Designs Inc.";
		case 0x06A8: return "GD Midea Air-Conditioning Equipment Co., Ltd.";
		case 0x0644: return "Apogee Instruments";
		case 0x0604: return "Cell2Jack LLC";
		case 0x05E0: return "Viper Design LLC";
		case 0x057C: return "Toor Technologies LLC";
		case 0x0518: return "MAMORIO.inc";
		case 0x0504: return "PHYPLUS Inc";
		case 0x04FF: return "Microsemi Corporation";
		case 0x04FE: return "Woosim Systems Inc.";
		case 0x04FD: return "Tapkey GmbH";
		case 0x04FC: return "SwingLync L. L. C.";
		case 0x04FB: return "Benchmark Drives GmbH & Co. KG";
		case 0x04FA: return "Androtec GmbH";
		case 0x04F9: return "Interactio";
		case 0x04F8: return "Convergence Systems Limited";
		case 0x04F7: return "Shenzhen Huiding Technology Co.,Ltd.";
		case 0x04F6: return "McLear Limited";
		case 0x04F5: return "Pirelli Tyre S.P.A.";
		case 0x04F4: return "ZanCompute Inc.";
		case 0x04F3: return "Cerevast Medical";
		case 0x04F2: return "InDreamer Techsol Private Limited";
		case 0x04F1: return "Theben AG";
		case 0x04F0: return "Kosi Limited";
		case 0x04EF: return "DaisyWorks, Inc";
		case 0x04EE: return "Auxivia";
		case 0x04ED: return "R9 Technology, Inc.";
		case 0x04EC: return "Motorola Solutions";
		case 0x04EB: return "Bird Home Automation GmbH";
		case 0x04EA: return "Pacific Bioscience Laboratories, Inc";
		case 0x04E9: return "Busch Jaeger Elektro GmbH";
		case 0x04E8: return "STABILO International";
		case 0x04E7: return "REHABTRONICS INC.";
		case 0x04E6: return "Smart Solution Technology, Inc.";
		case 0x04E5: return "Avack Oy";
		case 0x04E4: return "Woodenshark";
		case 0x04E3: return "Under Armour";
		case 0x04E2: return "EllieGrid";
		case 0x04E1: return "REACTEC LIMITED";
		case 0x04E0: return "Guardtec, Inc.";
		case 0x04DF: return "Emerson";
		case 0x04DE: return "Lutron Electronics Co., Inc.";
		case 0x04DD: return "4MOD Technology";
		case 0x04DC: return "IOTTIVE (OPC) PRIVATE LIMITED";
		case 0x04DB: return "Engineered Audio, LLC.";
		case 0x04DA: return "Franceschi Marina snc";
		case 0x04D9: return "RandMcNally";
		case 0x04D8: return "FUJIFILM Corporation";
		case 0x04D7: return "Blincam, Inc.";
		case 0x04D6: return "LUGLOC LLC";
		case 0x04D5: return "Gooee Limited";
		case 0x04D4: return "5th Element Ltd";
		case 0x04D3: return "Queercon, Inc";
		case 0x04D2: return "Anloq Technologies Inc.";
		case 0x04D1: return "KTS GmbH";
		case 0x04D0: return "Olympus Corporation";
		case 0x04CF: return "DOM Sicherheitstechnik GmbH & Co. KG";
		case 0x04CE: return "GOOOLED S.R.L.";
		case 0x04CD: return "Safetech Products LLC";
		case 0x04CC: return "Enflux Inc.";
		case 0x04CB: return "Novo Nordisk A/S";
		case 0x04CA: return "Steiner-Optik GmbH";
		case 0x04C9: return "Thornwave Labs Inc";
		case 0x04C8: return "Shanghai Flyco Electrical Appliance Co., Ltd.";
		case 0x04C7: return "Svantek Sp. z o.o.";
		case 0x04C6: return "Insta GmbH";
		case 0x04C5: return "Seibert Williams Glass, LLC";
		case 0x04C4: return "TeAM Hutchins AB";
		case 0x04C3: return "Mantracourt Electronics Limited";
		case 0x04C2: return "Dmet Products Corp.";
		case 0x04C1: return "Sospitas, s.r.o.";
		case 0x04C0: return "Statsports International";
		case 0x04BF: return "VIT Initiative, LLC";
		case 0x04BE: return "Averos FZCO";
		case 0x04BD: return "AlbynMedical";
		case 0x04BC: return "Draegerwerk AG & Co. KGaA";
		case 0x04BB: return "Neatebox Ltd";
		case 0x04BA: return "Crestron Electronics, Inc.";
		case 0x04B9: return "CSR Building Products Limited";
		case 0x04B8: return "Soraa Inc.";
		case 0x04B7: return "Analog Devices, Inc.";
		case 0x04B6: return "Diagnoptics Technologies";
		case 0x04B5: return "Swiftronix AB";
		case 0x04B4: return "Inuheat Group AB";
		case 0x04B3: return "mobike (Hong Kong) Limited";
		case 0x04B2: return "The Shadow on the Moon";
		case 0x04B1: return "Kartographers Technologies Pvt. Ltd.";
		case 0x04B0: return "Weba Sport und Med. Artikel GmbH";
		case 0x04AF: return "BIOROWER Handelsagentur GmbH";
		case 0x04AE: return "ERM Electronic Systems LTD";
		case 0x04AD: return "Shure Inc";
		case 0x04AC: return "Undagrid B.V.";
		case 0x04AB: return "Harbortronics, Inc.";
		case 0x04AA: return "LINKIO SAS";
		case 0x04A9: return "DISCOVERY SOUND TECHNOLOGY, LLC";
		case 0x04A8: return "BioTex, Inc.";
		case 0x04A7: return "Dallas Logic Corporation";
		case 0x04A6: return "Vinetech Co., Ltd";
		case 0x04A5: return "Guangzhou FiiO Electronics Technology Co.,Ltd";
		case 0x04A4: return "Herbert Waldmann GmbH & Co. KG";
		case 0x04A3: return "GT-tronics HK Ltd";
		case 0x04A2: return "ovrEngineered, LLC";
		case 0x04A1: return "PNI Sensor Corporation";
		case 0x04A0: return "Vypin, LLC";
		case 0x049F: return "tictote AB";
		case 0x049E: return "AND!XOR LLC";
		case 0x049D: return "Uhlmann & Zacher GmbH";
		case 0x049C: return "DyOcean";
		case 0x049B: return "nVisti, LLC";
		case 0x049A: return "Situne AS";
		case 0x0499: return "Ruuvi Innovations Ltd.";
		case 0x0498: return "METER Group, Inc. USA";
		case 0x0497: return "Cochlear Limited";
		case 0x0496: return "Polymorphic Labs LLC";
		case 0x0495: return "LMT Mercer Group, Inc";
		case 0x0494: return "SENNHEISER electronic GmbH & Co. KG";
		case 0x0493: return "Lynxemi Pte Ltd";
		case 0x0492: return "ADC Technology, Inc.";
		case 0x0491: return "SOREX - Wireless Solutions GmbH";
		case 0x0490: return "Matting AB";
		case 0x048F: return "BlueKitchen GmbH";
		case 0x048E: return "Companion Medical, Inc.";
		case 0x048D: return "S-Labs Sp. z o.o.";
		case 0x048C: return "Vectronix AG";
		case 0x048B: return "CP Electronics Limited";
		case 0x048A: return "Taelek Oy";
		case 0x0489: return "Igarashi Engineering";
		case 0x0488: return "Automotive Data Solutions Inc";
		case 0x0487: return "Centrica Connected Home";
		case 0x0486: return "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME";
		case 0x0485: return "SKIDATA AG";
		case 0x0484: return "Revol Technologies Inc";
		case 0x0483: return "Multi Care Systems B.V.";
		case 0x0482: return "POS Tuning Udo Vosshenrich GmbH & Co. KG";
		case 0x0481: return "Quintrax Limited";
		case 0x0480: return "Dynometrics Inc.";
		case 0x047F: return "Pro-Mark, Inc.";
		case 0x047E: return "OurHub Dev IvS";
		case 0x047D: return "Occly LLC";
		case 0x047C: return "POWERMAT LTD";
		case 0x047B: return "MIYOSHI ELECTRONICS CORPORATION";
		case 0x047A: return "Sinosun Technology Co., Ltd.";
		case 0x0479: return "mywerk system GmbH";
		case 0x0478: return "FarSite Communications Limited";
		case 0x0477: return "Blue Spark Technologies";
		case 0x0476: return "Oxstren Wearable Technologies Private Limited";
		case 0x0475: return "Icom inc.";
		case 0x0474: return "iApartment co., ltd.";
		case 0x0473: return "Steelcase, Inc.";
		case 0x0472: return "Control-J Pty Ltd";
		case 0x0471: return "TiVo Corp";
		case 0x0470: return "iDesign s.r.l.";
		case 0x046F: return "Develco Products A/S";
		case 0x046E: return "Pambor Ltd.";
		case 0x046D: return "BEGA Gantenbrink-Leuchten KG";
		case 0x046C: return "Qingdao Realtime Technology Co., Ltd.";
		case 0x046B: return "PMD Solutions";
		case 0x046A: return "INSIGMA INC.";
		case 0x0469: return "Palago AB";
		case 0x0468: return "Kynesim Ltd";
		case 0x0467: return "Codenex Oy";
		case 0x0466: return "CycleLabs Solutions inc.";
		case 0x0465: return "International Forte Group LLC";
		case 0x0464: return "Bellman & Symfon";
		case 0x0463: return "Fathom Systems Inc.";
		case 0x0462: return "Bonsai Systems GmbH";
		case 0x0461: return "vhf elektronik GmbH";
		case 0x0460: return "Kolibree";
		case 0x045F: return "Real Time Automation, Inc.";
		case 0x045E: return "Nuviz, Inc.";
		case 0x045D: return "Boston Scientific Corporation";
		case 0x045C: return "Delta T Corporation";
		case 0x045B: return "SPACEEK LTD";
		case 0x045A: return "2048450 Ontario Inc";
		case 0x0459: return "Lumenetix, Inc";
		case 0x0458: return "Mini Solution Co., Ltd.";
		case 0x0457: return "RF INNOVATION";
		case 0x0456: return "Nemik Consulting Inc";
		case 0x0455: return "Atomation";
		case 0x0454: return "Sphinx Electronics GmbH & Co KG";
		case 0x0453: return "GreenPeak Technologies BV";
		case 0x0452: return "Svep Design Center AB";
		case 0x0451: return "Tunstall Nordic AB";
		case 0x0450: return "Teenage Engineering AB";
		case 0x044F: return "TTS Tooltechnic Systems AG & Co. KG";
		case 0x044E: return "Xtrava Inc.";
		case 0x044D: return "VEGA Grieshaber KG";
		case 0x044C: return "LifeStyle Lock, LLC";
		case 0x044B: return "Nain Inc.";
		case 0x044A: return "SHIMANO INC.";
		case 0x0449: return "1UP USA.com llc";
		case 0x0448: return "Grand Centrix GmbH";
		case 0x0447: return "Fabtronics Australia Pty Ltd";
		case 0x0446: return "NETGEAR, Inc.";
		case 0x0445: return "Kobian Canada Inc.";
		case 0x0444: return "Metanate Limited";
		case 0x0443: return "Tucker International LLC";
		case 0x0442: return "SECOM CO., LTD.";
		case 0x0441: return "iProtoXi Oy";
		case 0x0440: return "Valencell, Inc.";
		case 0x043F: return "Tentacle Sync GmbH";
		case 0x043E: return "Thermomedics, Inc.";
		case 0x043D: return "Coiler Corporation";
		case 0x043C: return "DeLaval";
		case 0x043B: return "Appside co., ltd.";
		case 0x043A: return "Nuheara Limited";
		case 0x0439: return "Radiance Technologies";
		case 0x0438: return "Helvar Ltd";
		case 0x0437: return "eBest IOT Inc.";
		case 0x0436: return "Drayson Technologies (Europe) Limited";
		case 0x0435: return "Blocks Wearables Ltd.";
		case 0x0434: return "Hatch Baby, Inc.";
		case 0x0433: return "Pillsy Inc.";
		case 0x0432: return "Silk Labs, Inc.";
		case 0x0431: return "Amway Corporation";
		case 0x0430: return "SnapStyk Inc.";
		case 0x042F: return "Danfoss A/S";
		case 0x042E: return "MemCachier Inc.";
		case 0x042D: return "Meshtech AS";
		case 0x042C: return "Ticto N.V.";
		case 0x042B: return "iMicroMed Incorporated";
		case 0x042A: return "BD Medical";
		case 0x0429: return "Prolon Inc.";
		case 0x0428: return "SmallLoop, LLC";
		case 0x0427: return "Focus fleet and fuel management inc";
		case 0x0426: return "Husqvarna AB";
		case 0x0425: return "Unify Software and Solutions GmbH & Co. KG";
		case 0x0424: return "Trainesense Ltd.";
		case 0x0423: return "Chargifi Limited";
		case 0x0422: return "DELSEY SA";
		case 0x0421: return "Backbone Labs, Inc.";
		case 0x0420: return "TecBakery GmbH";
		case 0x041F: return "Kopin Corporation";
		case 0x041E: return "Dell Computer Corporation";
		case 0x041D: return "Benning Elektrotechnik und Elektronik GmbH & Co. KG";
		case 0x041C: return "WaterGuru, Inc.";
		case 0x041B: return "OrthoAccel Technologies";
		case 0x041A: return "Friday Labs Limited";
		case 0x0419: return "Novalogy LTD";
		case 0x0418: return "Alpine Electronics Inc.";
		case 0x0417: return "Fatigue Science";
		case 0x0416: return "SODA GmbH";
		case 0x0415: return "Uber Technologies Inc";
		case 0x0414: return "Lightning Protection International Pty Ltd";
		case 0x0413: return "Wireless Cables Inc";
		case 0x0412: return "SEFAM";
		case 0x0411: return "Luidia Inc";
		case 0x0410: return "Fender Musical Instruments";
		case 0x040F: return "CO-AX Technology, Inc.";
		case 0x040E: return "SKF (U.K.) Limited";
		case 0x040D: return "NorthStar Battery Company, LLC";
		case 0x040C: return "Senix Corporation";
		case 0x040B: return "Jana Care Inc.";
		case 0x040A: return "Openmatics";
		case 0x0409: return "AXIS";
		case 0x0408: return "ToGetHome Inc.";
		case 0x0407: return "Swiss Audio SA";
		case 0x0406: return "Airtago";
		case 0x0405: return "Vertex International, Inc.";
		case 0x0404: return "Authomate Inc";
		case 0x0403: return "Gantner Electronic GmbH";
		case 0x0402: return "Sears Holdings Corporation";
		case 0x0401: return "Relations Inc.";
		case 0x0400: return "i-developer IT Beratung UG";
		case 0x03EC: return "Jigowatts Inc.";
		case 0x0388: return "Kapsch TrafficCom AB";
		case 0x0324: return "Astro, Inc.";
		case 0x0304: return "Proxy Technologies, Inc.";
		case 0x02C0: return "Dash Robotics";
		case 0x025C: return "NetEase（Hangzhou）Network co.Ltd.";
		case 0x0204: return "Tapcentive Inc.";
		case 0x01F8: return "Anyka (Guangzhou) Microelectronics Technology Co, LTD";
		case 0x0194: return "Acoustic Stream Corporation";
		case 0x0130: return "Warehouse Innovations";
		case 0x0104: return "PLUS Location Systems Pty Ltd";
		case 0x00CC: return "Beats Electronics";
		case 0x0068: return "General Motors";
		case 0x004F: return "APT Ltd.";
		case 0x004E: return "Avago Technologies";
		case 0x004D: return "Staccato Communications, Inc.";
		case 0x004C: return "Apple, Inc.";
		case 0x004B: return "Continental Automotive Systems";
		case 0x004A: return "Accel Semiconductor Ltd.";
		case 0x0049: return "3DSP Corporation";
		case 0x0048: return "Marvell Technology Group Ltd.";
		case 0x0047: return "Bluegiga";
		case 0x0046: return "MediaTek, Inc.";
		case 0x0045: return "Atheros Communications, Inc.";
		case 0x0044: return "Socket Mobile";
		case 0x0043: return "PARROT AUTOMOTIVE SAS";
		case 0x0042: return "CONWISE Technology Corporation Ltd";
		case 0x0041: return "Integrated Silicon Solution Taiwan, Inc.";
		case 0x0040: return "Seiko Epson Corporation";
		case 0x0004: return "Toshiba Corp.";
		case 0xFFFF: return "<development>";

		/**
		 * Unique Identifier (UUID) assignments for Standards Development Organizations (SDOs)
		 * https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-sdos/
		 */
		case 0xFFF8: return "Mopria Alliance";
		case 0xFFF9: return "Fast IDentity Online Alliance (FIDO)";
		case 0xFFFA: return "ASTM International";
		case 0xFFFB: return "Thread Group, Inc.";
		case 0xFFFC: return "AirFuel Alliance";
		case 0xFFFD: return "Fast IDentity Online Alliance";
		case 0xFFFE: return "AirFuel Alliance (formerly Alliance for Wireless Power)";

		default: return "<unknown>";
	}
}
