#include <stdint.h>

// https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
// https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-members/
char const* GattServiceToString(uint16_t id) {
	switch (id) {
		/**
		 * Company identifiers assigned by the Bluetooth SIG to member companies
		 * https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
		 */
		case 0x1800: return "Generic Access";
		case 0x1801: return "Generic Attribute";
		case 0x1802: return "Immediate Alert";
		case 0x1803: return "Link Loss";
		case 0x1804: return "Tx Power";
		case 0x1805: return "Current Time Service";
		case 0x1806: return "Reference Time Update Service";
		case 0x1807: return "Next DST Change Service";
		case 0x1808: return "Glucose";
		case 0x1809: return "Health Thermometer";
		case 0x180A: return "Device Information";
		case 0x180D: return "Heart Rate";
		case 0x180E: return "Phone Alert Status Service";
		case 0x180F: return "Battery Service";
		case 0x1810: return "Blood Pressure";
		case 0x1811: return "Alert Notification Service";
		case 0x1812: return "Human Interface Device";
		case 0x1813: return "Scan Parameters";
		case 0x1814: return "Running Speed and Cadence";
		case 0x1815: return "Automation IO";
		case 0x1816: return "Cycling Speed and Cadence";
		case 0x1818: return "Cycling Power";
		case 0x1819: return "Location and Navigation";
		case 0x181A: return "Environmental Sensing";
		case 0x181B: return "Body Composition";
		case 0x181C: return "User Data";
		case 0x181D: return "Weight Scale";
		case 0x181E: return "Bond Management Service";
		case 0x181F: return "Continuous Glucose Monitoring";
		case 0x1820: return "Internet Protocol Support Service";
		case 0x1821: return "Indoor Positioning";
		case 0x1822: return "Pulse Oximeter Service";
		case 0x1823: return "HTTP Proxy";
		case 0x1824: return "Transport Discovery";
		case 0x1825: return "Object Transfer Service";
		case 0x1826: return "Fitness Machine";
		case 0x1827: return "Mesh Provisioning Service";
		case 0x1828: return "Mesh Proxy Service";
		case 0x1829: return "Reconnection Configuration";
		case 0x183A: return "Insulin Delivery";
		case 0x183B: return "Binary Sensor";
		case 0x183C: return "Emergency Configuration";

		/**
		 * 16-bit Universally Unique Identifier (UUID) for use with a custom GATT-based service defined by the member
		 * https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-members/
		 */
		case 0xFD77: return "Withings (0xFD77)";
		case 0xFD78: return "Withings (0xFD78)";
		case 0xFD79: return "Withings (0xFD79)";
		case 0xFD7A: return "Withings (0xFD7A)";
		case 0xFD7B: return "WYZE LABS, INC. (0xFD7B)";
		case 0xFD7C: return "Toshiba Information Systems(Japan) Corporation (0xFD7C)";
		case 0xFD7D: return "Center for Advanced Research Wernher Von Braun (0xFD7D)";
		case 0xFD7E: return "Samsung Electronics Co., Ltd. (0xFD7E)";
		case 0xFD7F: return "Husqvarna AB (0xFD7F)";
		case 0xFD80: return "Phindex Technologies, Inc (0xFD80)";
		case 0xFD81: return "CANDY HOUSE, Inc. (0xFD81)";
		case 0xFD82: return "Sony Corporation (0xFD82)";
		case 0xFD83: return "iNFORM Technology GmbH (0xFD83)";
		case 0xFD84: return "Tile, Inc. (0xFD84)";
		case 0xFD85: return "Husqvarna AB (0xFD85)";
		case 0xFD86: return "Abbott (0xFD86)";
		case 0xFD87: return "Google LLC (0xFD87)";
		case 0xFD88: return "Urbanminded LTD (0xFD88)";
		case 0xFD89: return "Urbanminded LTD (0xFD89)";
		case 0xFD8A: return "Signify Netherlands B.V. (0xFD8A)";
		case 0xFD8B: return "Jigowatts Inc. (0xFD8B)";
		case 0xFD8C: return "Google LLC (0xFD8C)";
		case 0xFD8D: return "quip NYC Inc. (0xFD8D)";
		case 0xFD8E: return "Motorola Solutions (0xFD8E)";
		case 0xFD8F: return "Matrix ComSec Pvt. Ltd. (0xFD8F)";
		case 0xFD90: return "Guangzhou SuperSound Information Technology Co.,Ltd (0xFD90)";
		case 0xFD91: return "Groove X, Inc. (0xFD91)";
		case 0xFD92: return "Qualcomm Technologies International, Ltd. (QTIL) (0xFD92)";
		case 0xFD93: return "Bayerische Motoren Werke AG (0xFD93)";
		case 0xFD94: return "Hewlett Packard Enterprise (0xFD94)";
		case 0xFD95: return "Rigado (0xFD95)";
		case 0xFD96: return "Google LLC (0xFD96)";
		case 0xFD97: return "June Life, Inc. (0xFD97)";
		case 0xFD98: return "Disney Worldwide Services, Inc. (0xFD98)";
		case 0xFD99: return "ABB Oy (0xFD99)";
		case 0xFD9A: return "Huawei Technologies Co., Ltd. (0xFD9A)";
		case 0xFD9B: return "Huawei Technologies Co., Ltd. (0xFD9B)";
		case 0xFD9C: return "Huawei Technologies Co., Ltd. (0xFD9C)";
		case 0xFD9D: return "Gastec Corporation (0xFD9D)";
		case 0xFD9E: return "The Coca-Cola Company (0xFD9E)";
		case 0xFD9F: return "VitalTech Affiliates LLC (0xFD9F)";
		case 0xFDA0: return "Secugen Corporation (0xFDA0)";
		case 0xFDA1: return "Groove X, Inc (0xFDA1)";
		case 0xFDA2: return "Groove X, Inc (0xFDA2)";
		case 0xFDA3: return "Inseego Corp. (0xFDA3)";
		case 0xFDA4: return "Inseego Corp. (0xFDA4)";
		case 0xFDA5: return "Neurostim OAB, Inc. (0xFDA5)";
		case 0xFDA6: return "WWZN Information Technology Company Limited (0xFDA6)";
		case 0xFDA7: return "WWZN Information Technology Company Limited (0xFDA7)";
		case 0xFDA8: return "PSA Peugeot Citroen (0xFDA8)";
		case 0xFDA9: return "Rhombus Systems, Inc. (0xFDA9)";
		case 0xFDAA: return "Xiaomi Inc. (0xFDAA)";
		case 0xFDAB: return "Xiaomi Inc. (0xFDAB)";
		case 0xFDAC: return "Tentacle Sync GmbH (0xFDAC)";
		case 0xFDAD: return "Houwa System Design, k.k. (0xFDAD)";
		case 0xFDAE: return "Houwa System Design, k.k. (0xFDAE)";
		case 0xFDAF: return "Wiliot LTD (0xFDAF)";
		case 0xFDB0: return "Proxy Technologies, Inc. (0xFDB0)";
		case 0xFDB1: return "Proxy Technologies, Inc. (0xFDB1)";
		case 0xFDB2: return "Portable Multimedia Ltd (0xFDB2)";
		case 0xFDB3: return "Audiodo AB (0xFDB3)";
		case 0xFDB4: return "HP Inc (0xFDB4)";
		case 0xFDB5: return "ECSG (0xFDB5)";
		case 0xFDB6: return "GWA Hygiene GmbH (0xFDB6)";
		case 0xFDB7: return "LivaNova USA Inc. (0xFDB7)";
		case 0xFDB8: return "LivaNova USA Inc. (0xFDB8)";
		case 0xFDB9: return "Comcast Cable Corporation (0xFDB9)";
		case 0xFDBA: return "Comcast Cable Corporation (0xFDBA)";
		case 0xFDBB: return "Profoto (0xFDBB)";
		case 0xFDBC: return "Emerson (0xFDBC)";
		case 0xFDBD: return "Clover Network, Inc. (0xFDBD)";
		case 0xFDBE: return "California Things Inc. (0xFDBE)";
		case 0xFDBF: return "California Things Inc. (0xFDBF)";
		case 0xFDC0: return "Hunter Douglas (0xFDC0)";
		case 0xFDC1: return "Hunter Douglas (0xFDC1)";
		case 0xFDC2: return "Baidu Online Network Technology (Beijing) Co., Ltd (0xFDC2)";
		case 0xFDC3: return "Baidu Online Network Technology (Beijing) Co., Ltd (0xFDC3)";
		case 0xFDC4: return "Simavita (Aust) Pty Ltd (0xFDC4)";
		case 0xFDC5: return "Automatic Labs (0xFDC5)";
		case 0xFDC6: return "Eli Lilly and Company (0xFDC6)";
		case 0xFDC7: return "Eli Lilly and Company (0xFDC7)";
		case 0xFDC8: return "Hach – Danaher (0xFDC8)";
		case 0xFDC9: return "Busch-Jaeger Elektro GmbH (0xFDC9)";
		case 0xFDCA: return "Fortin Electronic Systems (0xFDCA)";
		case 0xFDCB: return "Meggitt SA (0xFDCB)";
		case 0xFDCC: return "Shoof Technologies (0xFDCC)";
		case 0xFDCD: return "Qingping Technology (Beijing) Co., Ltd. (0xFDCD)";
		case 0xFDCE: return "SENNHEISER electronic GmbH & Co. KG (0xFDCE)";
		case 0xFDCF: return "Nalu Medical, Inc (0xFDCF)";
		case 0xFDD0: return "Huawei Technologies Co., Ltd (0xFDD0)";
		case 0xFDD1: return "Huawei Technologies Co., Ltd (0xFDD1)";
		case 0xFDD2: return "Bose Corporation (0xFDD2)";
		case 0xFDD3: return "FUBA Automotive Electronics GmbH (0xFDD3)";
		case 0xFDD4: return "LX Solutions Pty Limited (0xFDD4)";
		case 0xFDD5: return "Brompton Bicycle Ltd (0xFDD5)";
		case 0xFDD6: return "Ministry of Supply (0xFDD6)";
		case 0xFDD7: return "Emerson (0xFDD7)";
		case 0xFDD8: return "Jiangsu Teranovo Tech Co., Ltd. (0xFDD8)";
		case 0xFDD9: return "Jiangsu Teranovo Tech Co., Ltd. (0xFDD9)";
		case 0xFDDA: return "MHCS (0xFDDA)";
		case 0xFDDB: return "Samsung Electronics Co., Ltd. (0xFDDB)";
		case 0xFDDC: return "4iiii Innovations Inc. (0xFDDC)";
		case 0xFDDD: return "Arch Systems Inc (0xFDDD)";
		case 0xFDDE: return "Noodle Technology Inc. (0xFDDE)";
		case 0xFDDF: return "Harman International (0xFDDF)";
		case 0xFDE0: return "John Deere (0xFDE0)";
		case 0xFDE1: return "Fortin Electronic Systems (0xFDE1)";
		case 0xFDE2: return "Google Inc. (0xFDE2)";
		case 0xFDE3: return "Abbott Diabetes Care (0xFDE3)";
		case 0xFDE4: return "JUUL Labs, Inc. (0xFDE4)";
		case 0xFDE5: return "SMK Corporation (0xFDE5)";
		case 0xFDE6: return "Intelletto Technologies Inc (0xFDE6)";
		case 0xFDE7: return "SECOM Co., LTD (0xFDE7)";
		case 0xFDE8: return "Robert Bosch GmbH (0xFDE8)";
		case 0xFDE9: return "Spacesaver Corporation (0xFDE9)";
		case 0xFDEA: return "SeeScan, Inc (0xFDEA)";
		case 0xFDEB: return "Syntronix Corporation (0xFDEB)";
		case 0xFDEC: return "Mannkind Corporation (0xFDEC)";
		case 0xFDED: return "Pole Star (0xFDED)";
		case 0xFDEE: return "Huawei Technologies Co., Ltd. (0xFDEE)";
		case 0xFDEF: return "ART AND PROGRAM, INC. (0xFDEF)";
		case 0xFDF0: return "Google Inc. (0xFDF0)";
		case 0xFDF1: return "LAMPLIGHT Co.,Ltd (0xFDF1)";
		case 0xFDF2: return "AMICCOM Electronics Corporation (0xFDF2)";
		case 0xFDF3: return "Amersports (0xFDF3)";
		case 0xFDF4: return "O. E. M. Controls, Inc. (0xFDF4)";
		case 0xFDF5: return "Milwaukee Electric Tools (0xFDF5)";
		case 0xFDF6: return "AIAIAI ApS (0xFDF6)";
		case 0xFDF7: return "HP Inc. (0xFDF7)";
		case 0xFDF8: return "Onvocal (0xFDF8)";
		case 0xFDF9: return "INIA (0xFDF9)";
		case 0xFDFA: return "Tandem Diabetes Care (0xFDFA)";
		case 0xFDFB: return "Tandem Diabetes Care (0xFDFB)";
		case 0xFDFC: return "Optrel AG (0xFDFC)";
		case 0xFDFD: return "RecursiveSoft Inc. (0xFDFD)";
		case 0xFDFE: return "ADHERIUM(NZ) LIMITED (0xFDFE)";
		case 0xFDFF: return "OSRAM GmbH (0xFDFF)";
		case 0xFE00: return "Amazon.com Services, Inc. (0xFE00)";
		case 0xFE01: return "Duracell U.S. Operations Inc. (0xFE01)";
		case 0xFE02: return "Robert Bosch GmbH (0xFE02)";
		case 0xFE03: return "Amazon.com Services, Inc. (0xFE03)";
		case 0xFE04: return "OpenPath Security Inc (0xFE04)";
		case 0xFE05: return "CORE Transport Technologies NZ Limited (0xFE05)";
		case 0xFE06: return "Qualcomm Technologies, Inc. (0xFE06)";
		case 0xFE07: return "Sonos, Inc. (0xFE07)";
		case 0xFE08: return "Microsoft (0xFE08)";
		case 0xFE09: return "Pillsy, Inc. (0xFE09)";
		case 0xFE0A: return "ruwido austria gmbh (0xFE0A)";
		case 0xFE0B: return "ruwido austria gmbh (0xFE0B)";
		case 0xFE0C: return "Procter & Gamble (0xFE0C)";
		case 0xFE0D: return "Procter & Gamble (0xFE0D)";
		case 0xFE0E: return "Setec Pty Ltd (0xFE0E)";
		case 0xFE0F: return "Signify Netherlands B.V. (formerly Philips Lighting B.V.) (0xFE0F)";
		case 0xFE10: return "Lapis Semiconductor Co., Ltd. (0xFE10)";
		case 0xFE11: return "GMC-I Messtechnik GmbH (0xFE11)";
		case 0xFE12: return "M-Way Solutions GmbH (0xFE12)";
		case 0xFE13: return "Apple Inc. (0xFE13)";
		case 0xFE14: return "Flextronics International USA Inc. (0xFE14)";
		case 0xFE15: return "Amazon.com Services, Inc.. (0xFE15)";
		case 0xFE16: return "Footmarks, Inc. (0xFE16)";
		case 0xFE17: return "Telit Wireless Solutions GmbH (0xFE17)";
		case 0xFE18: return "Runtime, Inc. (0xFE18)";
		case 0xFE19: return "Google, Inc (0xFE19)";
		case 0xFE1A: return "Tyto Life LLC (0xFE1A)";
		case 0xFE1B: return "Tyto Life LLC (0xFE1B)";
		case 0xFE1C: return "NetMedia, Inc. (0xFE1C)";
		case 0xFE1D: return "Illuminati Instrument Corporation (0xFE1D)";
		case 0xFE1E: return "Smart Innovations Co., Ltd (0xFE1E)";
		case 0xFE1F: return "Garmin International, Inc. (0xFE1F)";
		case 0xFE20: return "Emerson (0xFE20)";
		case 0xFE21: return "Bose Corporation (0xFE21)";
		case 0xFE22: return "Zoll Medical Corporation (0xFE22)";
		case 0xFE23: return "Zoll Medical Corporation (0xFE23)";
		case 0xFE24: return "August Home Inc (0xFE24)";
		case 0xFE25: return "Apple, Inc. (0xFE25)";
		case 0xFE26: return "Google (0xFE26)";
		case 0xFE27: return "Google (0xFE27)";
		case 0xFE28: return "Ayla Networks (0xFE28)";
		case 0xFE29: return "Gibson Innovations (0xFE29)";
		case 0xFE2A: return "DaisyWorks, Inc. (0xFE2A)";
		case 0xFE2B: return "ITT Industries (0xFE2B)";
		case 0xFE2C: return "Google (0xFE2C)";
		case 0xFE2D: return "SMART INNOVATION Co.,Ltd (0xFE2D)";
		case 0xFE2E: return "ERi,Inc. (0xFE2E)";
		case 0xFE2F: return "CRESCO Wireless, Inc (0xFE2F)";
		case 0xFE30: return "Volkswagen AG (0xFE30)";
		case 0xFE31: return "Volkswagen AG (0xFE31)";
		case 0xFE32: return "Pro-Mark, Inc. (0xFE32)";
		case 0xFE33: return "CHIPOLO d.o.o. (0xFE33)";
		case 0xFE34: return "SmallLoop LLC (0xFE34)";
		case 0xFE35: return "HUAWEI Technologies Co., Ltd (0xFE35)";
		case 0xFE36: return "HUAWEI Technologies Co., Ltd (0xFE36)";
		case 0xFE37: return "Spaceek LTD (0xFE37)";
		case 0xFE38: return "Spaceek LTD (0xFE38)";
		case 0xFE39: return "TTS Tooltechnic Systems AG & Co. KG (0xFE39)";
		case 0xFE3A: return "TTS Tooltechnic Systems AG & Co. KG (0xFE3A)";
		case 0xFE3B: return "Dobly Laboratories (0xFE3B)";
		case 0xFE3C: return "alibaba (0xFE3C)";
		case 0xFE3D: return "BD Medical (0xFE3D)";
		case 0xFE3E: return "BD Medical (0xFE3E)";
		case 0xFE3F: return "Friday Labs Limited (0xFE3F)";
		case 0xFE40: return "Inugo Systems Limited (0xFE40)";
		case 0xFE41: return "Inugo Systems Limited (0xFE41)";
		case 0xFE42: return "Nets A/S (0xFE42)";
		case 0xFE43: return "Andreas Stihl AG & Co. KG (0xFE43)";
		case 0xFE44: return "SK Telecom (0xFE44)";
		case 0xFE45: return "Snapchat Inc (0xFE45)";
		case 0xFE46: return "B&O Play A/S (0xFE46)";
		case 0xFE47: return "General Motors (0xFE47)";
		case 0xFE48: return "General Motors (0xFE48)";
		case 0xFE49: return "SenionLab AB (0xFE49)";
		case 0xFE4A: return "OMRON HEALTHCARE Co., Ltd. (0xFE4A)";
		case 0xFE4B: return "Signify Netherlands B.V. (formerly Philips Lighting B.V.) (0xFE4B)";
		case 0xFE4C: return "Volkswagen AG (0xFE4C)";
		case 0xFE4D: return "Casambi Technologies Oy (0xFE4D)";
		case 0xFE4E: return "NTT docomo (0xFE4E)";
		case 0xFE4F: return "Molekule, Inc. (0xFE4F)";
		case 0xFE50: return "Google Inc. (0xFE50)";
		case 0xFE51: return "SRAM (0xFE51)";
		case 0xFE52: return "SetPoint Medical (0xFE52)";
		case 0xFE53: return "3M (0xFE53)";
		case 0xFE54: return "Motiv, Inc. (0xFE54)";
		case 0xFE55: return "Google Inc. (0xFE55)";
		case 0xFE56: return "Google Inc. (0xFE56)";
		case 0xFE57: return "Dotted Labs (0xFE57)";
		case 0xFE58: return "Nordic Semiconductor ASA (0xFE58)";
		case 0xFE59: return "Nordic Semiconductor ASA (0xFE59)";
		case 0xFE5A: return "Cronologics Corporation (0xFE5A)";
		case 0xFE5B: return "GT-tronics HK Ltd (0xFE5B)";
		case 0xFE5C: return "million hunters GmbH (0xFE5C)";
		case 0xFE5D: return "Grundfos A/S (0xFE5D)";
		case 0xFE5E: return "Plastc Corporation (0xFE5E)";
		case 0xFE5F: return "Eyefi, Inc. (0xFE5F)";
		case 0xFE60: return "Lierda Science & Technology Group Co., Ltd. (0xFE60)";
		case 0xFE61: return "Logitech International SA (0xFE61)";
		case 0xFE62: return "Indagem Tech LLC (0xFE62)";
		case 0xFE63: return "Connected Yard, Inc. (0xFE63)";
		case 0xFE64: return "Siemens AG (0xFE64)";
		case 0xFE65: return "CHIPOLO d.o.o. (0xFE65)";
		case 0xFE66: return "Intel Corporation (0xFE66)";
		case 0xFE67: return "Lab Sensor Solutions (0xFE67)";
		case 0xFE68: return "Capsule Technologies Inc. (0xFE68)";
		case 0xFE69: return "Capsule Technologies Inc. (0xFE69)";
		case 0xFE6A: return "Kontakt Micro-Location Sp. z o.o. (0xFE6A)";
		case 0xFE6B: return "TASER International, Inc. (0xFE6B)";
		case 0xFE6C: return "TASER International, Inc. (0xFE6C)";
		case 0xFE6D: return "The University of Tokyo (0xFE6D)";
		case 0xFE6E: return "The University of Tokyo (0xFE6E)";
		case 0xFE6F: return "LINE Corporation (0xFE6F)";
		case 0xFE70: return "Beijing Jingdong Century Trading Co., Ltd. (0xFE70)";
		case 0xFE71: return "Plume Design Inc (0xFE71)";
		case 0xFE72: return "Abbott (formerly St. Jude Medical, Inc.) (0xFE72)";
		case 0xFE73: return "Abbott (formerly St. Jude Medical, Inc.) (0xFE73)";
		case 0xFE74: return "unwire (0xFE74)";
		case 0xFE75: return "TangoMe (0xFE75)";
		case 0xFE76: return "TangoMe (0xFE76)";
		case 0xFE77: return "Hewlett-Packard Company (0xFE77)";
		case 0xFE78: return "Hewlett-Packard Company (0xFE78)";
		case 0xFE79: return "Zebra Technologies (0xFE79)";
		case 0xFE7A: return "Bragi GmbH (0xFE7A)";
		case 0xFE7B: return "Orion Labs, Inc. (0xFE7B)";
		case 0xFE7C: return "Telit Wireless Solutions (Formerly Stollmann E+V GmbH) (0xFE7C)";
		case 0xFE7D: return "Aterica Health Inc. (0xFE7D)";
		case 0xFE7E: return "Awear Solutions Ltd (0xFE7E)";
		case 0xFE7F: return "Doppler Lab (0xFE7F)";
		case 0xFE80: return "Doppler Lab (0xFE80)";
		case 0xFE81: return "Medtronic Inc. (0xFE81)";
		case 0xFE82: return "Medtronic Inc. (0xFE82)";
		case 0xFE83: return "Blue Bite (0xFE83)";
		case 0xFE84: return "RF Digital Corp (0xFE84)";
		case 0xFE85: return "RF Digital Corp (0xFE85)";
		case 0xFE86: return "HUAWEI Technologies Co., Ltd. (0xFE86)";
		case 0xFE87: return "Qingdao Yeelink Information Technology Co., Ltd. (0xFE87)";
		case 0xFE88: return "SALTO SYSTEMS S.L. (0xFE88)";
		case 0xFE89: return "B&O Play A/S (0xFE89)";
		case 0xFE8A: return "Apple, Inc. (0xFE8A)";
		case 0xFE8B: return "Apple, Inc. (0xFE8B)";
		case 0xFE8C: return "TRON Forum (0xFE8C)";
		case 0xFE8D: return "Interaxon Inc. (0xFE8D)";
		case 0xFE8E: return "ARM Ltd (0xFE8E)";
		case 0xFE8F: return "CSR (0xFE8F)";
		case 0xFE90: return "JUMA (0xFE90)";
		case 0xFE91: return "Shanghai Imilab Technology Co.,Ltd (0xFE91)";
		case 0xFE92: return "Jarden Safety & Security (0xFE92)";
		case 0xFE93: return "OttoQ In (0xFE93)";
		case 0xFE94: return "OttoQ In (0xFE94)";
		case 0xFE95: return "Xiaomi Inc. (0xFE95)";
		case 0xFE96: return "Tesla Motors Inc. (0xFE96)";
		case 0xFE97: return "Tesla Motors Inc. (0xFE97)";
		case 0xFE98: return "Currant Inc (0xFE98)";
		case 0xFE99: return "Currant Inc (0xFE99)";
		case 0xFE9A: return "Estimote (0xFE9A)";
		case 0xFE9B: return "Samsara Networks, Inc (0xFE9B)";
		case 0xFE9C: return "GSI Laboratories, Inc. (0xFE9C)";
		case 0xFE9D: return "Mobiquity Networks Inc (0xFE9D)";
		case 0xFE9E: return "Dialog Semiconductor B.V. (0xFE9E)";
		case 0xFE9F: return "Google (0xFE9F)";
		case 0xFEA0: return "Google (0xFEA0)";
		case 0xFEA1: return "Intrepid Control Systems, Inc. (0xFEA1)";
		case 0xFEA2: return "Intrepid Control Systems, Inc. (0xFEA2)";
		case 0xFEA3: return "ITT Industries (0xFEA3)";
		case 0xFEA4: return "Paxton Access Ltd (0xFEA4)";
		case 0xFEA5: return "GoPro, Inc. (0xFEA5)";
		case 0xFEA6: return "GoPro, Inc. (0xFEA6)";
		case 0xFEA7: return "UTC Fire and Security (0xFEA7)";
		case 0xFEA8: return "Savant Systems LLC (0xFEA8)";
		case 0xFEA9: return "Savant Systems LLC (0xFEA9)";
		case 0xFEAA: return "Google (0xFEAA)";
		case 0xFEAB: return "Nokia (0xFEAB)";
		case 0xFEAC: return "Nokia (0xFEAC)";
		case 0xFEAD: return "Nokia (0xFEAD)";
		case 0xFEAE: return "Nokia (0xFEAE)";
		case 0xFEAF: return "Nest Labs Inc (0xFEAF)";
		case 0xFEB0: return "Nest Labs Inc (0xFEB0)";
		case 0xFEB1: return "Electronics Tomorrow Limited (0xFEB1)";
		case 0xFEB2: return "Microsoft Corporation (0xFEB2)";
		case 0xFEB3: return "Taobao (0xFEB3)";
		case 0xFEB4: return "WiSilica Inc. (0xFEB4)";
		case 0xFEB5: return "WiSilica Inc. (0xFEB5)";
		case 0xFEB6: return "Vencer Co., Ltd (0xFEB6)";
		case 0xFEB7: return "Facebook, Inc. (0xFEB7)";
		case 0xFEB8: return "Facebook, Inc. (0xFEB8)";
		case 0xFEB9: return "LG Electronics (0xFEB9)";
		case 0xFEBA: return "Tencent Holdings Limited (0xFEBA)";
		case 0xFEBB: return "adafruit industries (0xFEBB)";
		case 0xFEBC: return "Dexcom Inc (0xFEBC)";
		case 0xFEBD: return "Clover Network, Inc (0xFEBD)";
		case 0xFEBE: return "Bose Corporation (0xFEBE)";
		case 0xFEBF: return "Nod, Inc. (0xFEBF)";
		case 0xFEC0: return "KDDI Corporation (0xFEC0)";
		case 0xFEC1: return "KDDI Corporation (0xFEC1)";
		case 0xFEC2: return "Blue Spark Technologies, Inc. (0xFEC2)";
		case 0xFEC3: return "360fly, Inc. (0xFEC3)";
		case 0xFEC4: return "PLUS Location Systems (0xFEC4)";
		case 0xFEC5: return "Realtek Semiconductor Corp. (0xFEC5)";
		case 0xFEC6: return "Kocomojo, LLC (0xFEC6)";
		case 0xFEC7: return "Apple, Inc. (0xFEC7)";
		case 0xFEC8: return "Apple, Inc. (0xFEC8)";
		case 0xFEC9: return "Apple, Inc. (0xFEC9)";
		case 0xFECA: return "Apple, Inc. (0xFECA)";
		case 0xFECB: return "Apple, Inc. (0xFECB)";
		case 0xFECC: return "Apple, Inc. (0xFECC)";
		case 0xFECD: return "Apple, Inc. (0xFECD)";
		case 0xFECE: return "Apple, Inc. (0xFECE)";
		case 0xFECF: return "Apple, Inc. (0xFECF)";
		case 0xFED0: return "Apple, Inc. (0xFED0)";
		case 0xFED1: return "Apple, Inc. (0xFED1)";
		case 0xFED2: return "Apple, Inc. (0xFED2)";
		case 0xFED3: return "Apple, Inc. (0xFED3)";
		case 0xFED4: return "Apple, Inc. (0xFED4)";
		case 0xFED5: return "Plantronics Inc. (0xFED5)";
		case 0xFED6: return "Broadcom (0xFED6)";
		case 0xFED7: return "Broadcom (0xFED7)";
		case 0xFED8: return "Google (0xFED8)";
		case 0xFED9: return "Pebble Technology Corporation (0xFED9)";
		case 0xFEDA: return "ISSC Technologies Corp. (0xFEDA)";
		case 0xFEDB: return "Perka, Inc. (0xFEDB)";
		case 0xFEDC: return "Jawbone (0xFEDC)";
		case 0xFEDD: return "Jawbone (0xFEDD)";
		case 0xFEDE: return "Coin, Inc. (0xFEDE)";
		case 0xFEDF: return "Design SHIFT (0xFEDF)";
		case 0xFEE0: return "Anhui Huami Information Technology Co., Ltd. (0xFEE0)";
		case 0xFEE1: return "Anhui Huami Information Technology Co., Ltd. (0xFEE1)";
		case 0xFEE2: return "Anki, Inc. (0xFEE2)";
		case 0xFEE3: return "Anki, Inc. (0xFEE3)";
		case 0xFEE4: return "Nordic Semiconductor ASA (0xFEE4)";
		case 0xFEE5: return "Nordic Semiconductor ASA (0xFEE5)";
		case 0xFEE6: return "Silvair, Inc. (0xFEE6)";
		case 0xFEE7: return "Tencent Holdings Limited. (0xFEE7)";
		case 0xFEE8: return "Quintic Corp. (0xFEE8)";
		case 0xFEE9: return "Quintic Corp. (0xFEE9)";
		case 0xFEEA: return "Swirl Networks, Inc. (0xFEEA)";
		case 0xFEEB: return "Swirl Networks, Inc. (0xFEEB)";
		case 0xFEEC: return "Tile, Inc. (0xFEEC)";
		case 0xFEED: return "Tile, Inc. (0xFEED)";
		case 0xFEEE: return "Polar Electro Oy (0xFEEE)";
		case 0xFEEF: return "Polar Electro Oy (0xFEEF)";
		case 0xFEF0: return "Intel (0xFEF0)";
		case 0xFEF1: return "CSR (0xFEF1)";
		case 0xFEF2: return "CSR (0xFEF2)";
		case 0xFEF3: return "Google (0xFEF3)";
		case 0xFEF4: return "Google (0xFEF4)";
		case 0xFEF5: return "Dialog Semiconductor GmbH (0xFEF5)";
		case 0xFEF6: return "Wicentric, Inc. (0xFEF6)";
		case 0xFEF7: return "Aplix Corporation (0xFEF7)";
		case 0xFEF8: return "Aplix Corporation (0xFEF8)";
		case 0xFEF9: return "PayPal, Inc. (0xFEF9)";
		case 0xFEFA: return "PayPal, Inc. (0xFEFA)";
		case 0xFEFB: return "Telit Wireless Solutions (Formerly Stollmann E+V GmbH) (0xFEFB)";
		case 0xFEFC: return "Gimbal, Inc. (0xFEFC)";
		case 0xFEFD: return "Gimbal, Inc. (0xFEFD)";
		case 0xFEFE: return "GN ReSound A/S (0xFEFE)";
		case 0xFEFF: return "GN Netcom (0xFEFF)";

		default: return "<unkown>";
	}
}
